In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

In [2]:
#algoritmo multiplicacion de matrices
A=np.array([[5., -4., -2.],[5.,-5.,4.],[2.,5.,-4.],[-5.,4.,3.],[3.,-4.,-3.]])
a=np.array([[5.],[-2.],[-3.]])
B=np.array([0,-1])
b=[]
C=[]
c=[]
A


array([[ 5., -4., -2.],
       [ 5., -5.,  4.],
       [ 2.,  5., -4.],
       [-5.,  4.,  3.],
       [ 3., -4., -3.]])

In [3]:
def multiplicar_matrices(A,B):
    #print(len(B))
    nueva_matriz=np.zeros((len(A),len(B[0])))
#tengo que correr las filas de a
#coger a11, a12, b12,b22
    if len(A[0])==len(B):
        for i in range(len(A)):
            for j in range(len(B[0])):
                valorij=np.sum(A[i,:]*B[:,j])
                nueva_matriz[i,j]=valorij
    else:
        print('El número de columnas de la primera matriz debe coincidir con el número de filas de la segunda matriz.')
    
    return nueva_matriz

In [4]:
print(multiplicar_matrices(A,a))

[[ 39.]
 [ 23.]
 [ 12.]
 [-42.]
 [ 32.]]


In [5]:
def Reducciongaussiano(M):
    n=len(M)
    hacer_pruebas=np.copy(M)
    M
    for j in range(n-1):
        for i in range(j+1,n):
            nueva_filai=hacer_pruebas[i,:]-((hacer_pruebas[i,j]/hacer_pruebas[j,j])*hacer_pruebas[j,:])
            #print('entra',hacer_pruebas[i,:],((hacer_pruebas[i,j]/hacer_pruebas[j,j])*hacer_pruebas[j,:]), type(nueva_filai))

            hacer_pruebas[i][:]=nueva_filai        
    return hacer_pruebas

In [12]:
M1=np.array([[3,1,-1,2],[1,-2,1,0],[4,-1,1,3]])
print(Reducciongaussiano(M1))


[[ 3  1 -1  2]
 [ 0 -2  1  0]
 [ 0  0  1  0]]


Como se puede notar, $F3=0$

Asi mismo, al despejar la segunda columa F2=0

Y $3\cdot F1=2$ entonces, $F1=6$

In [14]:
M2=np.array([[1,1,1,0],[0,-8,10,0],[4,-8,0,6]])
print(Reducciongaussiano(M2))
#Como se puede notar, -19*Ic=6, entonces Ic=-6/19
#Asi mismo, al despejar la segunda columa -8*Ib+10*Ic=0, entonces -8*Ib=-10*Ic, de modo que, Ib=Ic*10/8=(-6/19)*(10/8)=-60/152
#E Ia + Ib+Ic=0, entonces Ia= -Ib-Ic=-60/152-(-6/19)= (-1140+912)/2888=-228


print(152*19, 152*6, 60*19, 152*6-60*19)

[[  1   1   1   0]
 [  0  -8  10   0]
 [  0   0 -19   6]]
2888 912 1140 -228


Como se puede notar: $-19 \cdot Ic=6$, entonces $Ic=-6/19$

Asi mismo, al despejarla segunda columa:

$-8\cdot Ib+10\cdot Ic=0$,

Entonces: $-8\cdot Ib=-10\cdot Ic$, de modo que:

$Ib=Ic\cdot 10/8=(-6/19)\cdot(10/8)=-60/152$, Asi:

$Ia + Ib+Ic=0$, entonces:

$Ia= -Ib-Ic=-60/152-(-6/19)= (-1140+912)/2888=-228$