In [76]:
import numpy as np
import sympy as sym

In [77]:
sigmax=np.array([[0,1],\
           [1,0]])

sigmay= np.array([[0,-1j],\
           [1j,0]])

sigmaz= np.array([[1,0],\
           [0,-1]])


In [78]:
def conmutar(A,B):
    a=np.dot(A,B)
    b=np.dot(B,A)
    c=a-b
    return c

In [79]:
conmutar(sigmax,sigmay)
#Se espera que el resultado sea 2i*sigmaz

array([[0.+2.j, 0.+0.j],
       [0.+0.j, 0.-2.j]])

In [80]:
conmutar(sigmax,sigmaz)
#Se espera que el resultado sea -2i*sigmay

array([[ 0, -2],
       [ 2,  0]])

In [81]:
conmutar(sigmay,sigmay)
#Se espera que el resultado sea 0

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [82]:
def comprobacion(x,y,z):
    sigma=[x,y,z]
    contador=0.
    for i in range(len(sigma)):
        for j in range(len(sigma)):
            conm=conmutar(sigma[i],sigma[j])
            a=[]
            if i==j:
                a=np.array([[0,0],\
                    [0,0]])
            elif i==0 and j==1:    #Casos con permutación par
                a=2j*z
            elif i==1 and j==2:
                a=2j*x
            elif i==2 and j==0:
                a=2j*y

            elif i==2 and j==1:    #Casos con permutación impar
                a=-2j*x
            elif i==0 and j==2:
                a=-2j*y
            elif i==1 and j==0:
                a=-2j*z
            dif=np.max(np.abs(conm-a))
            if dif==0.:
                contador += 1  #Va a aumentar cada vez que se confirme el algebra de Lie
    
    return contador

In [83]:
comprobacion(sigmax,sigmay,sigmaz)
#Se espera que de 9, comprobando los 9 casos posibles

9.0