In [146]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

In [147]:
A=np.array([[0.2, 0.1, 1, 1, 0],\
           [0.1, 4, -1, 1, -1],\
           [1, -1, 60, 0, -2],\
            [1, 1, 0, 8, 4],\
            [0, -1, -2, 4, 700]])

b=np.array([[1], [2], [3], [4], [5]])
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [148]:
np.dot(A,b)

array([[   7.4],
       [   4.1],
       [ 169. ],
       [  55. ],
       [3508. ]])

In [149]:
def desConjugado(x0,A,b,tol=0.01,itmax=10):
    r=[]
    p=[]
    x=[]
    beta=[0]

    r.append(np.dot(A,x0)-b)
    x.append(x0)
    p.append(-r[0])
    error=1.
    k=0.

    q=-np.dot(np.transpose(r[0]),p[0])
    w=np.dot(A,p[0])
    e=np.dot(np.transpose(p[0]),w)
    a=[]
    i=1
    while error>tol and k<itmax:
        #for i in range(1,itmax):
        #print(i)
            
        num=-np.dot(np.transpose(r[i-1]),p[i-1])
        inter=np.dot(A,p[i-1])
        den=np.dot(np.transpose(p[i-1]),inter)
        a.append(num/den)

        x.append(x[i-1]+a[i-1]*p[i-1])
        r.append(np.dot(A,x[i])-b)

        inter2=np.dot(A,p[i-1])
        num2=np.dot(np.transpose(r[i]),inter2)
        den2=np.dot(np.transpose(p[i-1]),inter2)
        #print(num2/den2)
        beta.append(num2/den2)

        p.append(-r[i]+beta[i]*p[i-1])
        k+=1

        error=np.max(np.abs(r[i]))
        i+=1
    return x[-1],k
        

In [150]:
x0=np.array([[1], [1], [1], [1], [1]])
sol, it=desConjugado(x0,A,b)
it

5.0

In [151]:
sol

array([[ 7.85971308],
       [ 0.42292641],
       [-0.07359224],
       [-0.54064302],
       [ 0.01062614]])