In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))
import numpy as np
import matplotlib.pyplot as plt
import math

In [16]:
C=729/10000
G = np.array([lambda t: np.sin(t)**6- C*np.sin(t)**2-C])

In [26]:
def GetF(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    
    v[0] = G[0](r[0])
        
    return v

In [38]:
def GetJacobian(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = (f[i](rf[0]) - f[i](rb[0]))/(2*h)
    print(J, 'j')        
    
    return J

In [43]:
def NewtonRaphson(G,r,itmax=1000,error=1e-9):
    
    it = 0
    d = 1.
    dvector = []
    
    while d > error and it < itmax:
        
        # Vector actual
        rc = r
        
        F = GetF(G,rc)
        J = GetJacobian(G,rc)
        #InvJ = np.linalg.inv(J)
        InvJ= (1/np.abs(J))*(J)
        
        r = rc - np.dot(InvJ,F)
        
        diff = r - rc
        
        d = np.max( np.abs(diff) )
        
        dvector.append(d)
        #print(dvector)
        
        it += 1
    
    print(it)
    return r,dvector

In [49]:
raices=[]
seed=[-10,-5.,-1.,1.,5.,10.,20.]
for i in seed:
    r, dvector = NewtonRaphson(G,np.array([i]))
    raices.append(r)
raices

[[-5915.15812916]] j
1
[[1.34032552]] j
[[0.30785123]] j
[[0.43083705]] j
[[0.51786106]] j
[[0.56612641]] j
[[0.58874102]] j
[[0.59838573]] j
[[0.60232013]] j
[[0.60389479]] j
[[0.60452012]] j
[[0.60476768]] j
[[0.60486556]] j
[[0.60490424]] j
[[0.60491953]] j
[[0.60492557]] j
[[0.60492795]] j
[[0.60492889]] j
[[0.60492927]] j
[[0.60492941]] j
[[0.60492947]] j
[[0.6049295]] j
[[0.6049295]] j
[[0.60492951]] j
23
[[-1.30139002]] j
[[-0.62989192]] j
[[-0.61444413]] j
[[-0.60863773]] j
[[-0.6063868]] j
[[-0.60550405]] j
[[-0.60515631]] j
[[-0.60501908]] j
[[-0.60496489]] j
[[-0.60494349]] j
[[-0.60493503]] j
[[-0.60493169]] j
[[-0.60493037]] j
[[-0.60492985]] j
[[-0.60492964]] j
[[-0.60492956]] j
[[-0.60492953]] j
[[-0.60492952]] j
[[-0.60492951]] j
19
[[1.30139002]] j
[[0.62989192]] j
[[0.61444413]] j
[[0.60863773]] j
[[0.6063868]] j
[[0.60550405]] j
[[0.60515631]] j
[[0.60501908]] j
[[0.60496489]] j
[[0.60494349]] j
[[0.60493503]] j
[[0.60493169]] j
[[0.60493037]] j
[[0.60492985]] j
[[0.

[array([-10.]),
 array([-5.52220886]),
 array([-0.76097645]),
 array([0.76097645]),
 array([5.52220886]),
 array([10.18575441]),
 array([19.61053237])]

In [ ]:
r